# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hg < Formula
  desc "Hypergraph & HoTT tooling in Go"
  homepage "https://github.com/watchthelight/HypergraphGo"
  version "1.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.1/hg_1.9.1_darwin_amd64.tar.gz"
      sha256 "c396fd0f7b4112ab7e3818aeb97633ce2d0c1171659f05ca006672bfd8d9bd3f"

      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.1/hg_1.9.1_darwin_arm64.tar.gz"
      sha256 "accf746fedd10e86c5f688295ae10d3058e2491ed714ac5105766311488d920d"

      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.1/hg_1.9.1_linux_amd64.tar.gz"
      sha256 "c790e76bcb4a44764d4ada279aed0f93dc67f3c32f009f61e85112407a3938cc"
      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.1/hg_1.9.1_linux_arm64.tar.gz"
      sha256 "8622f377fd42587dbf9931f9c32b21af2e3ea9619b74eeb034b6143ad0964a93"
      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
  end
end
