# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hg < Formula
  desc "Hypergraph & HoTT tooling in Go"
  homepage "https://github.com/watchthelight/HypergraphGo"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.0/hg_1.9.0_darwin_amd64.tar.gz"
      sha256 "13a0f28dff984368fdb225f99e4139f84dea3b8f6b1528eb4e1e4d5dcdcc4434"

      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.0/hg_1.9.0_darwin_arm64.tar.gz"
      sha256 "75c2497e4ee731154e7bc456da11614fcceb60d997b8f10ac5ad1faec868326e"

      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.0/hg_1.9.0_linux_amd64.tar.gz"
      sha256 "5563841a64203aedec42b3737d3b13893065df6fb2232069e005cd8fed1c1df0"
      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/watchthelight/HypergraphGo/releases/download/v1.9.0/hg_1.9.0_linux_arm64.tar.gz"
      sha256 "f8ea6670389d271e42658b7e5f1e4a5a43343e5777e0faeb01ab3af11a1ed814"
      define_method(:install) do
        bin.install "hg"
        bin.install "hottgo"
      end
    end
  end
end
